baseURL: 'https://antiidiotidiots.github.io/'
languageCode: en-us
title: Anti-Idiot Idiots
theme: PaperMod

params:
  title: We are the Anti-Idiot Idiots
  description: "This is our website"
  env: production # Enables enchanced SEO
  images: [static\img\nasa-earth.jpg]
  profileMode:
    enabled: true
    title: "We are the Anti-Idiot Idiots"
    subtitle: "This is our website"
    buttons:
      - name: Blog Posts
        url: "/posts/"
      - name: Who are we?
        url: "/about/us"
  socialIcons: # Show the respective social icon linked to the corresponding URL
    - name: github
      url: "https://github.com/antiidiotidiots"

  cover:
    linkFullImages: true # Clicking a post's cover image opens the image in a new tab
  # Other settings
  ShowBreadcrumbs: true # Show the path to a page'
  ShowReadingTime: true # Show the page's reading time
  # ShowShareButtons: true # Show the share buttons
  # ShowPostNavLinks: true # Show navigation links under a post
outputs:
    home:
        - HTML
        - JSON
menu:
  main:
    - indentifier: github
      name: Github
      url: https://github.com/antiidiotidiots
      weight: 2
    - indentifier: search
      name: Search
      url: search/
      weight: 1
